server:
  port: 8084
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
spring:
  application:
      name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: VIEWER-SERVICE
          uri: lb://VIEWER-SERVICE
          predicates:
            - Path=/viewers/**
          filters:
            - AuthenticationFilter


        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**
          filters:
            - AuthenticationFilter


        - id: SERIES-SERVICE
          uri: lb://SERIES-SERVICE
          predicates:
            - Path=/api/series/**
          filters:
            - AuthenticationFilter


        - id: SECURITY-SERVICE
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**


eureka:
  instance:
    prefer-Ip-Address: true
  client:
    fetch-registry-with-eureka: true
    register-with-eureka: true
  service-url:
    defaultZone: http://localhost:8761/eureka/

